version: '3.8'

services:
  iris_model_training:
    build:
      context: .
      dockerfile: Dockerfile.train
    volumes:
      - ./logs:/app/logs
      - dvc_config:/app/.dvc
    secrets:
      - dvc_config_local
    env_file:
      - .env
    restart: no
    command: ["sh", "-c", "cp /run/secrets/dvc_config_local /app/.dvc/config.local && python src/models/train_model.py"]

secrets:
  dvc_config_local:
    file: .dvc/config.local

volumes:
  dvc_config:

networks:
  default:
    name: iris_model_network